### ISSUE TITLE
The extension has stopped working in the Canary.

### ISSUE THREAD

**Issue by vsemozhetbyt** [davidparsson/scrollbar-anywhere#56]
- Mouse button used when scrolling: Right
- Chrome version: 58.0.2994.0 Canary (64-bit)
- Operating system:  Windows 7 x64

The extension works only on the settings page, on other pages the cursor shape changes, but no scrolling happens.

FWIW, I've checked on 'Collect errors' on the extensions page and here is the report on Scrollbar Anywhere:

![sa](https://cloud.githubusercontent.com/assets/10393198/22387991/f0d93ee8-e4e6-11e6-909a-d0fdf4a1333d.png)

**Comment by davidparsson** [comment]
@vsemozhetbyt, is this still an issue for you?

**Comment by vsemozhetbyt** [comment]
@davidparsson Yes, with Chrome Canary 59.0.3033.0 it is the same.

**Comment by davidparsson** [comment]
Ok, thank you.

**Comment by davidparsson** [comment]
@vsemozhetbyt, I'm actually unable to reproduce this issue on Chrome Canary 59.0.3037.1 on Windows. For me it all works just fine. Have you tried disabling any other extensions?

**Comment by davidparsson** [comment]
To be clear, `portId_` is undefined for me as well, but that does not seem to cause any errors or affect scrolling. I'll investigate a bit more though.

**Comment by davidparsson** [comment]
Ok, so the error you saw should only have prevented settings from being updated in other tabs when they were changed. That's fixed in 37343b4, but I doubt that will solve your issues.

If you want to try out the that and give me feedback, you can download the source from here and load the `src` directory as an unpacked chrome extension. Remember to disable the "real" extension before doing this.

**Comment by davidparsson** [comment]
Also, please verify that the configured mouse button is what you think it is. 🙂 

I'm closing this since I'm unable to reproduce it, but feel free to reopen if you find any more details.

**Comment by vsemozhetbyt** [comment]
@davidparsson 
1. I've found out the cause. This flag being enabled prevent the extension from scrolling the page: chrome://flags/#enable-experimental-web-platform-features . So maybe you could ignore this case. Sorry.

2. I still get these errors with the current `src` folder as extensions:

![1](https://cloud.githubusercontent.com/assets/10393198/23822603/27dce826-0658-11e7-80e0-3d0035645408.png)
![2](https://cloud.githubusercontent.com/assets/10393198/23822604/27e42758-0658-11e7-87be-b9e19ff73339.png)

But it seems they do not prevent anything important from working,

Thank you for your work and time.

**Comment by vsemozhetbyt** [comment]
FWIW:

About the key: https://www.chromium.org/blink/runtime-enabled-features
List of the features behind the key (many concerning scrolling): https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/RuntimeEnabledFeatures.json5

**Comment by davidparsson** [comment]
Thanks you!

**Comment by vsemozhetbyt** [comment]
@davidparsson It seems these 'errors' are not actually errors.  I see no real error messages in the developer tools, only these debug info messages. Maybe this 'errors' window simply collects any console messages from extensions as well as real errors.
